/** Shared content types. All page content is data-driven from `src/data`. */

export interface ImageAsset {
  src: string;
  /** Descriptive alt text. Never leave this empty for content imagery. */
  alt: string;
}

export type CategorySlug =
  | "sofas"
  | "beds"
  | "dining"
  | "living-room"
  | "bedroom"
  | "wardrobes"
  | "tv-units"
  | "chairs"
  | "custom";

export interface Category {
  slug: CategorySlug;
  title: string;
  /** Short line shown on the category card. */
  description: string;
  image: ImageAsset;
  href: string;
  /** Sofas and beds are the hero categories and get a larger cell. */
  emphasis: "primary" | "secondary";
  /** Example pieces listed under the card title. */
  pieces: string[];
}

export type ProductGroup = "sofas" | "beds" | "more";

export interface Product {
  id: string;
  /** URL segment, derived from `name`. See `src/lib/slug.ts`. */
  slug: string;
  name: string;
  /** e.g. "Three-seater · Fabric" */
  style: string;
  /** Visible category label. */
  category: string;
  group: ProductGroup;
  description: string;
  image: ImageAsset;
  /**
   * 1200x630 crop of `image`, used only as the social share card. Attached in
   * `src/data/products.ts` from the slug; generated by
   * `scripts/generate-share-images.mjs`. Falls back to `image` when absent.
   */
  shareImage?: ImageAsset;
  /** Two to four short specification-style bullets. */
  highlights: string[];
  /**
   * Short facets used by the category chips on the listing pages, e.g.
   * "L-shape", "Leather", "Storage". Keep them consistent within a group -
   * the chip row is built from the union of the tags actually present.
   */
  tags: string[];
  /**
   * Optional, only rendered when present. Deliberately left undefined for the
   * sample catalogue: no prices are invented anywhere in this project.
   */
  price?: string;
  /** Small badge, e.g. "Made to order". */
  badge?: string;
  featured?: boolean;
}

export interface GalleryItem {
  id: string;
  image: ImageAsset;
  caption: string;
  /** Controls the cell footprint in the masonry-style gallery grid. */
  shape: "tall" | "wide" | "square";
}

export interface Testimonial {
  id: string;
  quote: string;
  name: string;
  location?: string;
  /** The piece they bought, e.g. "L-shape sectional". */
  product?: string;
  /**
   * Whole stars out of 5. Only set this from a rating the customer actually
   * gave you - it is rendered as a visible claim.
   */
  rating?: 1 | 2 | 3 | 4 | 5;
  /** Overrides the initials shown in the avatar. Defaults to the name. */
  initials?: string;
}

export interface Feature {
  id: string;
  title: string;
  description: string;
  icon: "design" | "craft" | "comfort" | "custom" | "consult" | "delivery";
}

export interface FaqItem {
  id: string;
  question: string;
  answer: string;
}

/**
 * One half of the sofa / bed split feature. These are the two categories the
 * business leads with, so they get their own richer shape rather than reusing
 * `Category`: a promise line, supporting points and their own WhatsApp opener.
 */
export interface PrimaryFeature {
  slug: "sofas" | "beds";
  /** Card title, e.g. "Sofas". */
  title: string;
  /** Four or five words that sum the category up, e.g. "Designed for living." */
  promise: string;
  description: string;
  href: string;
  image: ImageAsset;
  /** Three short facets listed under the copy. */
  points: string[];
  /** Context-varied CTA label - never the same wording on both halves. */
  ctaLabel: string;
  /** Completes "Ask about ..." on the WhatsApp button. Lower case. */
  enquiryLabel: string;
}

/* ---------------------------------------------------------------------------
 * Blog
 *
 * Articles are authored as structured content rather than as markup strings.
 * That keeps them type-safe, keeps every internal link a real `next/link`, and
 * lets the renderer own typography so an author can never break the page - the
 * same reasoning that keeps product copy in `src/data/products.ts`.
 * ------------------------------------------------------------------------- */

export type BlogCategorySlug =
  | "buying-guides"
  | "sofas-living-room"
  | "beds-bedroom"
  | "small-spaces"
  | "furniture-care"
  | "delhi-ncr";

export interface BlogCategory {
  slug: BlogCategorySlug;
  /** Display name, used as the H1 on the archive and in breadcrumbs. */
  title: string;
  /** Short line under the archive heading and on the chip row's landing page. */
  description: string;
  /** Meta description for /blog/category/<slug>. Written per category. */
  metaDescription: string;
}

/**
 * One run of inline text. A bare string is plain copy; the object form carries
 * a link (internal paths and absolute URLs both work) or bold emphasis.
 */
export type InlineNode = string | { text: string; href?: string; strong?: boolean };

/** A paragraph or list item: a sequence of inline runs. */
export type RichText = InlineNode[];

/** The blocks an article body can be built from. */
export type ArticleBlock =
  | { type: "paragraph"; text: RichText }
  /** Only h2 and h3: the article title is the page's only h1. */
  | { type: "heading"; level: 2 | 3; text: string }
  | { type: "list"; ordered?: boolean; items: RichText[] }
  /** Term-and-explanation pairs, rendered as a description list. */
  | { type: "definitions"; items: { term: string; text: RichText }[] }
  | { type: "table"; caption: string; columns: string[]; rows: string[][] }
  /** Aside for a caveat or a rule of thumb worth pulling out of the flow. */
  | { type: "callout"; title: string; text: RichText }
  | { type: "checklist"; title: string; items: string[] }
  | { type: "image"; image: ImageAsset; caption: string }
  /**
   * In-article conversion block. `whatsappMessage` is passed through
   * `whatsappHref()` so the opener arrives with the article's context; `link`
   * points at the range page the article is actually about.
   */
  | {
      type: "cta";
      title: string;
      text: string;
      whatsappMessage: string;
      whatsappLabel: string;
      link?: { href: string; label: string };
    };

export interface BlogPost {
  slug: string;
  /** The visible H1. */
  title: string;
  /** `<title>` when it should differ from the H1 - usually to add keywords. */
  seoTitle?: string;
  /** Meta description. Unique per article; 140-160 characters. */
  description: string;
  /** Card and archive copy. Shorter and more conversational than the meta. */
  excerpt: string;
  category: BlogCategorySlug;
  /** Free-form topic tags. Also used to match guides to a range page. */
  tags: string[];
  /** ISO date, e.g. "2026-09-07". */
  publishedAt: string;
  /** ISO date. Set it whenever the article is meaningfully revised. */
  updatedAt?: string;
  image: ImageAsset;
  /**
   * 1200x630 crop of `image`, used only as the social share card. Attached in
   * `src/data/blog/index.ts` from the slug; generated by
   * `scripts/generate-share-images.mjs`. Falls back to `image` when absent.
   */
  shareImage?: ImageAsset;
  /**
   * The place this article is genuinely written for, when it has one. Used in
   * the article meta line and as `spatialCoverage` in the structured data.
   * Leave it out unless the content is actually specific to that place.
   */
  location?: string;
  /** Promotes the article into the featured row on /blog. */
  featured?: boolean;
  /** Three or four sentences a reader can act on without reading the whole piece. */
  takeaways: string[];
  blocks: ArticleBlock[];
  /**
   * Only add questions the article really answers: `FAQPage` structured data
   * is emitted from this list, and it must match visible content.
   */
  faqs?: FaqItem[];
  /** Curated links into the range. Meaningful anchor text, not a link dump. */
  relatedLinks?: { href: string; label: string; description: string }[];
  /** Slugs of related articles. Falls back to the same category when unset. */
  relatedPosts?: string[];
}
